// <auto-generated />
using System;
using System.Collections.Generic;
using AiTeam.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AiTeam.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260524162847_Stage87TalentTokenLimitsAndAgentConfigDrop")]
    partial class Stage87TalentTokenLimitsAndAgentConfigDrop
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AiTeam.Data.AppSetting", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Key");

                    b.ToTable("app_settings", (string)null);
                });

            modelBuilder.Entity("AiTeam.Data.BossCommandLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("CeoResponseRaw")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Images")
                        .HasColumnType("jsonb");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.ToTable("boss_command_logs", (string)null);
                });

            modelBuilder.Entity("AiTeam.Data.BossInteraction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("AgentName")
                        .HasColumnType("text");

                    b.Property<string>("AvailableActionsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ContextJson")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal?>("DiscordMessageId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("InteractionType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("ProcessedByBot")
                        .HasColumnType("boolean");

                    b.Property<string>("Project")
                        .HasColumnType("text");

                    b.Property<DateTime?>("RespondedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ResponseAction")
                        .HasColumnType("text");

                    b.Property<string>("ResponseContent")
                        .HasColumnType("text");

                    b.Property<string>("ResponseSource")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SystemNotes")
                        .HasColumnType("text");

                    b.Property<Guid?>("TaskGroupId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("TaskItemId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DiscordMessageId");

                    b.HasIndex("TaskItemId");

                    b.HasIndex("Status", "CreatedAt");

                    b.HasIndex("TaskGroupId", "InteractionType")
                        .IsUnique()
                        .HasDatabaseName("ix_boss_interactions_pending_per_group_type")
                        .HasFilter("\"Status\" = 'pending'");

                    b.ToTable("boss_interactions", (string)null);
                });

            modelBuilder.Entity("AiTeam.Data.CeoConversation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("UserId", "SessionId");

                    b.ToTable("ceo_conversations", (string)null);
                });

            modelBuilder.Entity("AiTeam.Data.CeoMemory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "IsActive");

                    b.ToTable("ceo_memories", (string)null);
                });

            modelBuilder.Entity("AiTeam.Data.PetraInbox", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Attachments")
                        .HasColumnType("jsonb");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeadAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("EnqueuedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text");

                    b.Property<int>("MaxAttempts")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("NextRetryAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("PetraSessionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserInput")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Status", "EnqueuedAt")
                        .HasDatabaseName("ix_petra_inbox_status_enqueued");

                    b.HasIndex("Status", "NextRetryAt")
                        .HasDatabaseName("ix_petra_inbox_status_next_retry");

                    b.ToTable("petra_inbox", (string)null);
                });

            modelBuilder.Entity("AiTeam.Data.PetraSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ReplanIteration")
                        .HasColumnType("integer");

                    b.Property<string>("ResultPrUrl")
                        .HasColumnType("text");

                    b.Property<decimal>("SessionCostUsd")
                        .HasColumnType("numeric");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("TaskGroupId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("TaskGroupId");

                    b.HasIndex("Status", "CreatedAt");

                    b.ToTable("petra_sessions", (string)null);
                });

            modelBuilder.Entity("AiTeam.Data.PetraSessionMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid");

                    b.Property<string>("ToolCallId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("SessionId", "CreatedAt");

                    b.ToTable("petra_session_messages", (string)null);
                });

            modelBuilder.Entity("AiTeam.Data.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RepoUrl")
                        .HasColumnType("text");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uuid");

                    b.Property<string>("TechStack")
                        .HasColumnType("jsonb");

                    b.HasKey("Id");

                    b.HasIndex("TeamId");

                    b.ToTable("projects", (string)null);
                });

            modelBuilder.Entity("AiTeam.Data.Rule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("AgentName")
                        .HasColumnType("text");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<Guid?>("TeamId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TeamId");

                    b.ToTable("rules", (string)null);
                });

            modelBuilder.Entity("AiTeam.Data.SkillPrompt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedByUser")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("PromptBody")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SkillName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("VersionNumber")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SkillName")
                        .IsUnique()
                        .HasDatabaseName("ix_skill_prompts_active_per_skill")
                        .HasFilter("\"IsActive\" = true");

                    b.HasIndex("SkillName", "VersionNumber");

                    b.ToTable("skill_prompts", (string)null);
                });

            modelBuilder.Entity("AiTeam.Data.Talent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("DailyTokenLimitK")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Model")
                        .HasColumnType("text");

                    b.Property<int?>("MonthlyTokenLimitK")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<string>("Provider")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_talents_name_global")
                        .HasFilter("\"ProjectId\" IS NULL");

                    b.HasIndex("ProjectId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_talents_project_name_per_project")
                        .HasFilter("\"ProjectId\" IS NOT NULL");

                    b.ToTable("talents", (string)null);
                });

            modelBuilder.Entity("AiTeam.Data.TalentMemory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("ProjectId")
                        .HasColumnType("uuid");

                    b.PrimitiveCollection<List<string>>("Tags")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<Guid>("TalentId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("TalentId", "CreatedAt");

                    b.HasIndex("TalentId", "Key")
                        .IsUnique()
                        .HasDatabaseName("ix_talent_memories_talent_key_global")
                        .HasFilter("\"ProjectId\" IS NULL");

                    b.HasIndex("TalentId", "Key", "ProjectId")
                        .IsUnique()
                        .HasDatabaseName("ix_talent_memories_talent_key_project")
                        .HasFilter("\"ProjectId\" IS NOT NULL");

                    b.ToTable("talent_memories", (string)null);
                });

            modelBuilder.Entity("AiTeam.Data.TalentPrompt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("PersonaBody")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TalentId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("VersionNumber")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TalentId")
                        .IsUnique()
                        .HasDatabaseName("ix_talent_prompts_active_per_talent")
                        .HasFilter("\"IsActive\" = true");

                    b.HasIndex("TalentId", "VersionNumber");

                    b.ToTable("talent_prompts", (string)null);
                });

            modelBuilder.Entity("AiTeam.Data.TalentSkill", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("boolean");

                    b.Property<string>("Model")
                        .HasColumnType("text");

                    b.Property<int>("Priority")
                        .HasColumnType("integer");

                    b.Property<string>("Provider")
                        .HasColumnType("text");

                    b.Property<string>("SkillName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TalentId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TalentId", "SkillName")
                        .IsUnique();

                    b.ToTable("talent_skills", (string)null);
                });

            modelBuilder.Entity("AiTeam.Data.TaskGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("ActiveOrchestration")
                        .HasColumnType("text");

                    b.Property<string>("ArchiveContent")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DesignFrameworkStateJson")
                        .HasColumnType("text");

                    b.Property<string>("DesignMeetingLog")
                        .HasColumnType("text");

                    b.Property<string>("DesignPlan")
                        .HasColumnType("text");

                    b.Property<int>("DesignRound")
                        .HasColumnType("integer");

                    b.Property<string>("DevPlan")
                        .HasColumnType("text");

                    b.Property<string>("DevPlanAppealLog")
                        .HasColumnType("text");

                    b.Property<int>("DevPlanAppealRoundA")
                        .HasColumnType("integer");

                    b.Property<int>("DevPlanRevision")
                        .HasColumnType("integer");

                    b.Property<string>("DevPrUrl")
                        .HasColumnType("text");

                    b.Property<bool?>("EpicPaused")
                        .HasColumnType("boolean");

                    b.Property<int>("FixIteration")
                        .HasColumnType("integer");

                    b.Property<string>("FrameworkAppealStateJson")
                        .HasColumnType("text");

                    b.Property<string>("ImplementationNote")
                        .HasColumnType("text");

                    b.Property<string>("InterventionReason")
                        .HasColumnType("text");

                    b.Property<bool>("IsPaused")
                        .HasColumnType("boolean");

                    b.Property<string>("IssueUrls")
                        .HasColumnType("jsonb");

                    b.Property<string>("KickoffFrameworkStateJson")
                        .HasColumnType("text");

                    b.Property<string>("KickoffMeetingLog")
                        .HasColumnType("text");

                    b.Property<int>("KickoffRound")
                        .HasColumnType("integer");

                    b.Property<int?>("LastIssueCreatedRound")
                        .HasColumnType("integer");

                    b.Property<string>("LastReviewBody")
                        .HasColumnType("text");

                    b.Property<Guid?>("ParentGroupId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("PausedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PausedBy")
                        .HasColumnType("text");

                    b.Property<string>("PendingStepsJson")
                        .HasColumnType("text");

                    b.Property<string>("PhaseDescription")
                        .HasColumnType("text");

                    b.Property<int?>("PhaseNumber")
                        .HasColumnType("integer");

                    b.Property<string>("PipelineFrameworkStateJson")
                        .HasColumnType("text");

                    b.Property<string>("Project")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<int>("QaFixRound")
                        .HasColumnType("integer");

                    b.Property<string>("ReviewAppealLog")
                        .HasColumnType("text");

                    b.Property<int>("ReviewAppealRoundA")
                        .HasColumnType("integer");

                    b.Property<bool>("SkipReviewerAfterArbitration")
                        .HasColumnType("boolean");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TaskPlan")
                        .HasColumnType("text");

                    b.Property<string>("TestReport")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UiSpecContent")
                        .HasColumnType("text");

                    b.Property<string>("UiSpecPath")
                        .HasColumnType("text");

                    b.Property<string>("WorkflowType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.HasIndex("Status");

                    b.ToTable("task_groups", (string)null);
                });

            modelBuilder.Entity("AiTeam.Data.TaskItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("AssignedAgent")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<Guid?>("GroupId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<string>("QueueStatus")
                        .HasColumnType("text");

                    b.Property<DateTime?>("QueuedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("TeamId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TriggeredBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("WorkflowAgentKey")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.HasIndex("ProjectId");

                    b.HasIndex("TeamId");

                    b.ToTable("tasks", (string)null);
                });

            modelBuilder.Entity("AiTeam.Data.TaskLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Agent")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Payload")
                        .HasColumnType("jsonb");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Step")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TaskId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TaskId");

                    b.ToTable("task_logs", (string)null);
                });

            modelBuilder.Entity("AiTeam.Data.TaskMemory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedByTalent")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("PetraSessionId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("PetraSessionId", "CreatedAt");

                    b.HasIndex("PetraSessionId", "Key")
                        .IsUnique()
                        .HasDatabaseName("ix_task_memories_session_key");

                    b.ToTable("task_memories", (string)null);
                });

            modelBuilder.Entity("AiTeam.Data.Team", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("teams", (string)null);
                });

            modelBuilder.Entity("AiTeam.Data.TokenLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("AgentName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("CacheCreationTokens")
                        .HasColumnType("integer");

                    b.Property<int?>("CacheReadTokens")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("InputTokens")
                        .HasColumnType("integer");

                    b.Property<bool>("IsEstimated")
                        .HasColumnType("boolean");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("OutputTokens")
                        .HasColumnType("integer");

                    b.Property<Guid?>("PetraSessionId")
                        .HasColumnType("uuid");

                    b.Property<int?>("Round")
                        .HasColumnType("integer");

                    b.Property<string>("Stage")
                        .HasColumnType("text");

                    b.Property<Guid?>("TaskId")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("TotalCostUsd")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)");

                    b.HasKey("Id");

                    b.HasIndex("PetraSessionId");

                    b.HasIndex("TaskId");

                    b.ToTable("token_logs", (string)null);
                });

            modelBuilder.Entity("AiTeam.Data.BossInteraction", b =>
                {
                    b.HasOne("AiTeam.Data.TaskGroup", "TaskGroup")
                        .WithMany()
                        .HasForeignKey("TaskGroupId");

                    b.HasOne("AiTeam.Data.TaskItem", "TaskItem")
                        .WithMany()
                        .HasForeignKey("TaskItemId");

                    b.Navigation("TaskGroup");

                    b.Navigation("TaskItem");
                });

            modelBuilder.Entity("AiTeam.Data.PetraSession", b =>
                {
                    b.HasOne("AiTeam.Data.TaskGroup", "TaskGroup")
                        .WithMany()
                        .HasForeignKey("TaskGroupId");

                    b.Navigation("TaskGroup");
                });

            modelBuilder.Entity("AiTeam.Data.PetraSessionMessage", b =>
                {
                    b.HasOne("AiTeam.Data.PetraSession", "Session")
                        .WithMany("Messages")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("AiTeam.Data.Project", b =>
                {
                    b.HasOne("AiTeam.Data.Team", "Team")
                        .WithMany("Projects")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Team");
                });

            modelBuilder.Entity("AiTeam.Data.Rule", b =>
                {
                    b.HasOne("AiTeam.Data.Team", "Team")
                        .WithMany()
                        .HasForeignKey("TeamId");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("AiTeam.Data.Talent", b =>
                {
                    b.HasOne("AiTeam.Data.Project", "ProjectRef")
                        .WithMany()
                        .HasForeignKey("ProjectId");

                    b.Navigation("ProjectRef");
                });

            modelBuilder.Entity("AiTeam.Data.TalentMemory", b =>
                {
                    b.HasOne("AiTeam.Data.Talent", "Talent")
                        .WithMany()
                        .HasForeignKey("TalentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Talent");
                });

            modelBuilder.Entity("AiTeam.Data.TalentPrompt", b =>
                {
                    b.HasOne("AiTeam.Data.Talent", "Talent")
                        .WithMany()
                        .HasForeignKey("TalentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Talent");
                });

            modelBuilder.Entity("AiTeam.Data.TalentSkill", b =>
                {
                    b.HasOne("AiTeam.Data.Talent", "Talent")
                        .WithMany("Skills")
                        .HasForeignKey("TalentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Talent");
                });

            modelBuilder.Entity("AiTeam.Data.TaskGroup", b =>
                {
                    b.HasOne("AiTeam.Data.Project", "ProjectRef")
                        .WithMany()
                        .HasForeignKey("ProjectId");

                    b.Navigation("ProjectRef");
                });

            modelBuilder.Entity("AiTeam.Data.TaskItem", b =>
                {
                    b.HasOne("AiTeam.Data.TaskGroup", "Group")
                        .WithMany("Tasks")
                        .HasForeignKey("GroupId");

                    b.HasOne("AiTeam.Data.Project", "Project")
                        .WithMany("Tasks")
                        .HasForeignKey("ProjectId");

                    b.HasOne("AiTeam.Data.Team", "Team")
                        .WithMany("Tasks")
                        .HasForeignKey("TeamId");

                    b.Navigation("Group");

                    b.Navigation("Project");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("AiTeam.Data.TaskLog", b =>
                {
                    b.HasOne("AiTeam.Data.TaskItem", "Task")
                        .WithMany("Logs")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Task");
                });

            modelBuilder.Entity("AiTeam.Data.TaskMemory", b =>
                {
                    b.HasOne("AiTeam.Data.PetraSession", null)
                        .WithMany()
                        .HasForeignKey("PetraSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AiTeam.Data.TokenLog", b =>
                {
                    b.HasOne("AiTeam.Data.TaskItem", "Task")
                        .WithMany()
                        .HasForeignKey("TaskId");

                    b.Navigation("Task");
                });

            modelBuilder.Entity("AiTeam.Data.PetraSession", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("AiTeam.Data.Project", b =>
                {
                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("AiTeam.Data.Talent", b =>
                {
                    b.Navigation("Skills");
                });

            modelBuilder.Entity("AiTeam.Data.TaskGroup", b =>
                {
                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("AiTeam.Data.TaskItem", b =>
                {
                    b.Navigation("Logs");
                });

            modelBuilder.Entity("AiTeam.Data.Team", b =>
                {
                    b.Navigation("Projects");

                    b.Navigation("Tasks");
                });
#pragma warning restore 612, 618
        }
    }
}
